spring:
  application:
    name: EHR Transfer Service
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      skip:
        in-tests: true
  aop:
    auto: true
logging:
  include-application-name: true